# Default values for kiosk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

env: {}

nodeSelector: {}

readinessProbe:
  enabled: true

livenessProbe:
  enabled: true

kiosk:
  command: 
  - /kiosk
  args: []
  resources:
    limits:
      memory: 512Mi
      cpu: "1"
    requests:
      memory: 128Mi
      cpu: 50m

webhook:
  create: true

apiservice:
  create: true
  port: 8443

serviceAccount:
  name: serviceaccount
  create: true
  clusterRole: cluster-admin

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443
  targetPort: 9443

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
