apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "kiosk.fullname" . }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ template "kiosk.fullname" . }}"
  labels:
    app: {{ template "kiosk.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "kiosk.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-accountquota
  failurePolicy: Fail
  name: vaccountquota.kb.io
  rules:
  - apiGroups:
    - config.kiosk.sh
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - accountquotas
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "kiosk.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-pod
  failurePolicy: Fail
  name: vpods.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "kiosk.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-templateinstance
  failurePolicy: Fail
  name: vtemplateinstance.kb.io
  rules:
  - apiGroups:
    - config.kiosk.sh
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - templateinstances
